version: "3"

services:
  app:
    build: .
    privileged: true
    volumes: 
      - ${VOLUME_SALTPAY}:/var/www/html/:cached
    environment: 
      - ENV=${ENV}
      - TZ=Europe/Lisbon
      - DB=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    hostname: ${HOSTNAME_SALTPAY}
    cap_add: 
      - SYS_ADMIN
      - DAC_READ_SEARCH
    ports: 
      - "${PORT_SALTPAY}:80"
    depends_on: 
      - db
  db:
    image: mariadb:10.6.0
    restart: always
    environment:
      MARIADB_DATABASE: "${MYSQL_DATABASE}"
      MARIADB_USER: "${MYSQL_USER}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports: 
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_HOST}:/var/lib/mysql

