name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    -uses: shivammathur/setup-php@v2
    - name: Run tests
      run: libs/vendor/bin/phpunit  --configuration Tests/phpunit.xml
